version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nerdneilsfield"
    labels:
      - "dependencies"
      - "rust"
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "nerdneilsfield"
    labels:
      - "dependencies"
      - "github-actions"