[package]
name = "tagbox-gui"
version = "0.1.0"
edition = "2021"
authors = ["Qi Deng<dengqi935@gmail.com>"]
description = "Core library for TagBox file management system"

[dependencies]
fltk = { version = "1.4", features = ["fltk-bundled"] }
fltk-table = "0.3"
