[package]
name = "test_load"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tagbox-core = { path = "../tagbox-core" }
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"